[package]
name = "v5"
version = "0.1.0"
edition = "2024"

[dependencies]
rocketmq = {version = "5.0.0"}
time = { version = "0.3", features = ["local-offset"] }
tokio = {version = "1", features = ["full"]}
